### ISSUE TITLE
Mangel på <noscript>-tags skaper usikkerhet på om en rapport er sendt på grades.no

### ISSUE THREAD

**Issue by Jonta** [dotkom/gradestats#22]
- Firefox
- NoScript uten å tillate grades.no
- Skriv rapport og send på https://grades.no/report
- Siden ser ut til å begå en slags refresh
- Vet ikke om rapporten er sendt

- Tillat grades.no sin JS
- Skriv og send rapport igjen
- Få grønn "Takk for tilbakemeldingen!"

**Comment by oleast** [comment]
Fikset i frontend repo: https://github.com/dotkom/gradestats-app/pull/39
