### ISSUE TITLE
500-error på grades.no ved forsøk på å rapportere feil

### ISSUE THREAD

**Issue by Jonta** [dotkom/gradestats#7]
**Describe the bug**
Fylte om dummy-data i feltene fordi feilen jeg skulle rapportere ikke angikk et fag

**To Reproduce**
1. IT1337 som kode
2. V2020 som semester
3. Påpeke at det ikke ser ut til å finnes en måte å rapportere eller pull-requeste språkfeil på

**Expected behavior**
"Takk for rapporten!"

**Smartphone:**
 - Device: Moto G7 Power (XT1955-4)
 - OS: Android 9
 - Browser: Firefox
 - Version: 68.7.0

**Comment by oleast** [comment]
Takk for tilbakemeldingen!

Det skal nå være mulig å sende inn tilbakemeldinger via nettsiden igjen.

Merk at siden er helt ny bak kulissene, men at designet ikke har blitt oppdatert nevnverdig (ennå...). Det er kanskje noen andre småproblemer som oppstår, men vi er nå i bedre stand til å ta hånd om dem.
